version: "3.3"

services:
  web:
    image: 'web_dev'
    build:
      context: .
    ports:
      - 3000:3000 # rails
      - 3035:3035 # webpacker dev server
    env_file:
      - ".env"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
    command: start-server
    stdin_open: true
    tty: true

  background_job:
    image: web_dev
    links:
      - db
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/tmp
    env_file:
      - ".env"
    command: start-background-job

  db:
    image: postgres:9.6-alpine
    env_file:
      - ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  selenium_chrome:
    image: selenium/standalone-chrome:3.141.59
    ports:
      - 4444:4444

volumes:
  postgres_data:
