version: "3.3"

services:
  web:
    image: 'web_dev'
    build:
      context: .
    ports:
      - 3000:3000
    env_file:
      - ".env"
    volumes:
      - .:/usr/src/app
    command: start-server
    stdin_open: true
    tty: true

  background_job:
    image: web_dev
    links:
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/tmp
    env_file:
      - ".env"
    command: start-background-job

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  selenium-hub:
    image: selenium/hub:3.141.59-mercury
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-mercury
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
