version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@2
  kubernetes: circleci/kubernetes@0.11.2

jobs:
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.7.2-node
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: breaded
          POSTGRES_DB: breaded_test
          POSTGRES_PASSWORD: password
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      DB_HOST: 127.0.0.1
      DB_USERNAME: breaded
      DB_PASSWORD: password
      RAILS_ENV: test
      HOST_URL: "http://localhost"
      STRIPE_SECRET_KEY: "sk_test_51HeFW8I4g05dLynGWnnUZjNGP6uDnqvCDUGGmqcHhlJyQpP7NS3ZEYIVbQ3DtHFoWffWbFSc8Zd4EVZt3i4gwLtG00Sva77iue"
      STRIPE_PUBLISHABLE_KEY: "pk_test_51HeFW8I4g05dLynGZJRfdRRsDN27EsdFzXdp2mKrQ58QqhgVBIPENjzPUFvbQs1PAph7ZkVKSnSKyIAhpmnQFMI6007G0NWpTK"
      STRIPE_WEBHOOK_SECRET: "whsec_3Bi3nIoiFoj95LZ5HzQl8jzbiULxSAVP"

    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            - rails-breaded-bundle-{{ checksum "Gemfile" }}
            - rails-breaded-bundle-
      - run:
          name: Bundle Install
          command: bundle install
      - save_cache:
          key: rails-breaded-bundle-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:rebuild
      - run:
          name: Run tests
          command: rake test

  build_release:
    docker:
      - image: cimg/ruby:2.7.2-node
    steps:
      - run:
          name: Build docker image
          command: docker build -f Dockerfile.production . -t breaded-production:$CIRCLE_SHA1 --build-arg COMMIT_HASH=$CIRCLE_SHA1
      - run:
          name: Tag docker image 
          command: docker tag breaded-production:$CIRCLE_SHA1 registry.digitalocean.com/breaded/breaded-production:$CIRCLE_SHA1
      - run:
          name: Push docker image
          command: docker push registry.digitalocean.com/breaded/breaded-production:$CIRCLE_SHA1

  deploy:
    docker:
      - image: cimg/ruby:2.7.2-node
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run:
          name: Update web deployment
          command: kubectl set image deployment/web web=registry.digitalocean.com/breaded/breaded-production:$CIRCLE_SHA1
      - run:
          name: Update background job deployment
          command: kubectl set image deployment/background-job background-job=registry.digitalocean.com/breaded/breaded-production:$CIRCLE_SHA1

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          requires:
            - build
      - build_release:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build_release
          filters:
            branches:
              only: master
