apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - args:
        - start-server
        env:
        - name: RAILS_ENV
          valueFrom:
            configMapKeyRef:
              key: RAILS_ENV
              name: web-env
        image: registry.digitalocean.com/breaded/breaded-production
        name: web
        ports:
        - containerPort: 3000
          name: web
          protocol: TCP
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
