apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - args:
        - start-server
        envFrom:
          - configMapRef:
              name: breaded-config
          - secretRef:
              name: breaded-secrets
        image: registry.digitalocean.com/breaded/breaded-production:fb6f057
        resources:
          limits:
            memory: 300Mi
            cpu: 250m
          requests:
            cpu: 250m
            memory: 300Mi
        name: web
        ports:
        - containerPort: 3000
          name: web
          protocol: TCP
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /commit.txt
            port: web
          failureThreshold: 3
          periodSeconds: 20
          initialDelaySeconds: 120
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /commit.txt
            port: web
          failureThreshold: 3
          periodSeconds: 20
          initialDelaySeconds: 60
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
