apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - args:
        - start-server
        envFrom:
          - configMapRef:
              name: breaded-config
          - secretRef:
              name: breaded-secrets
        image: registry.digitalocean.com/breaded/breaded-production:d67e437
        name: web
        ports:
        - containerPort: 3000
          name: web
          protocol: TCP
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /pages/commit
            port: web
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 60
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /pages/commit
            port: web
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 30
      restartPolicy: Always
