default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: host.docker.internal
  port: 5432
  username: breaded
  password: password

development:
  <<: *default
  database: breaded_development

test:
  <<: *default
  database: breaded_test

production:
  <<: *default
  database: breaded_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials.db.try(:[], :db_host) %>
  port: <%= Rails.application.credentials.db.try(:[], :db_port) %>
  username: <%= Rails.application.credentials.db.try(:[], :db_username) %>
  password: <%= Rails.application.credentials.db.try(:[], :db_password) %>
