default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials.db[:db_host] %>
  port: <%= Rails.application.credentials.db[:db_port] %>
  username: <%= Rails.application.credentials.db[:db_username] %>
  password: <%= Rails.application.credentials.db[:db_password] %>

development:
  <<: *default
  database: breaded_development

test:
  <<: *default
  database: breaded_test

production:
  <<: *default
  database: breaded_production
