test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

digitalocean:
  service: S3
  endpoint: <%= ENV["STORAGE_ENDPOINT"] %>
  access_key_id: <%= ENV["STORAGE_KEY"] %>
  secret_access_key: <%= ENV["STORAGE_ACCESS_KEY"] %>
  region: ams3
  bucket: <%= ENV["STORAGE_BUCKET"] %>
  public: true
